[package]
name = "rb64"
description = "Base 64"
version = "0.2.1"
edition = "2021"
authors = ["Saúl Valdelvira <saul@saulv.es>"]
license = "MIT"
readme = "README"

[lib]
crate-type = [ "lib", "cdylib", "staticlib" ]

[dependencies]
ratatui = { version = ">=0.28.1", optional = true }
tui-textarea = { version = ">=0.6.1", optional = true }

[build-dependencies]
cbindgen = { version = "0.24.0", optional = true }

[features]
default = []
no-std = []
tui = ["dep:ratatui", "dep:tui-textarea"]
bindings = ["dep:cbindgen"]

